### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by HorusApl** [Browsit/mcMMOQuestsModule#5]
This error spams console on basically any interaction by the player:

[21:53:57 WARN]: [Quests] Plugin Quests v5.0.1-b454 generated an exception while executing task 488
java.lang.IncompatibleClassChangeError: Expected static method 'com.gmail.nossr50.datatypes.party.Party com.gmail.nossr50.party.PartyManager.getParty(org.bukkit.entity.Player)'
        at me.pikamug.unite.api.objects.plugins.PartyProvider_mcMMO.getPartyName(PartyProvider_mcMMO.java:132) ~[Unite-1.1.7.jar:?]
        at me.pikamug.unite.api.objects.plugins.PartyProvider_mcMMO.getPartyId(PartyProvider_mcMMO.java:141) ~[Unite-1.1.7.jar:?]
        at me.pikamug.quests.player.BukkitQuester.getMultiplayerQuesters(BukkitQuester.java:4428) ~[Quests-5.0.1.jar:?]
        at me.pikamug.quests.player.BukkitQuester.dispatchMultiplayerEverything(BukkitQuester.java:4353) ~[Quests-5.0.1.jar:?]
        at me.pikamug.quests.listeners.BukkitPlayerListener.lambda$playerMove$13(BukkitPlayerListener.java:1000) ~[Quests-5.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by HorusApl** [comment]
mcMMO version 2.2.004
mcMMO Overhaul Quests Module 2.1
Unite version 1.1.7
Quests version 5.0.1-b454
Server version: git-Purpur-2151 (MC: 1.20.4)*

**Comment by HorusApl** [comment]
Still getting similar errors. Seems to happen on basically any block place, interact, jump, etc. https://mclo.gs/B5jgzfM
https://mclo.gs/YpRukGQ

Tried on a blank quests.yml to make sure it wasn't somehow a conflicting reward or otherwise issue as I've sometimes seen happen using the editor, and issue occurs with fresh files.

**Comment by Browsit** [comment]
@HorusApl On closer inspection, this appears to be an issue with Unite. Please report it on the developer's issue tracker - https://github.com/PikaMug/Unite
